meta_product_name: "Friendy App"
meta_title: "Try and be a rainbow, in someone else’s cloud - be a Friendy!"
meta_description: "Contactlessly donate to homeless individuals and help them off the streets."
meta_image: "banner_og.jpg" # should exist in `app/assets/images/`
