meta_product_name: "Friendy App"
meta_title: "The best you can find on the internet"
meta_description: "Lorem Ipsum bla bla Lorem Ipsum bla bla Lorem Ipsum bla bla"
meta_image: "banner.jpg" # should exist in `app/assets/images/`
